### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LucidMeta** [mahjerion/Craft-to-Exile-Harmony#140]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version e.g. 2.2.3
 - World Type on boot
 - RAM Allocation 9GB

**Describe the bug**
Crashes on launch before it even shows up

**To Reproduce**
1. Launch The Game

**Expected behavior**
Launch the game properly

**Additional Information (screen shots, etc.)**
Message it gives me `java.lang.RuntimeException: Error creating Mixin config mixins.cardinal_components_scoreboard.json for mod cardinal-components-scoreboard
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:90)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config mixins.cardinal_components_scoreboard.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:88)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The specified resource 'mixins.cardinal_components_scoreboard.json' was invalid or could not be read
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1290)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more
`

**Comment by mahjerion** [comment]
seems to be ok for me, how did you install it?
