### ISSUE TITLE
[BUG] Game Crash

### ISSUE THREAD

**Issue by JFMillerUSA** [mahjerion/Craft-to-Exile-Harmony#4]
**Technical Specs (please complete the following information):**
 - Craft to Exile [Harmony] 1.0.5b
 - Single
 - RAM Allocation 4GB

**Describe the bug**
Crash trying to load world

---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 9/25/20 4:09 PM
Description: mouseClicked event handler

java.lang.IllegalStateException: failed to create a child event loop
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at net.minecraft.class_3242.method_14348(class_3242.java:56)
	at net.minecraft.class_3528.method_15332(class_3528.java:16)
	at net.minecraft.class_3242.method_14353(class_3242.java:138)
	at net.minecraft.class_310.method_29610(class_310.java:1839)
	at net.minecraft.class_310.method_29607(class_310.java:1700)
	at net.minecraft.class_525.method_2736(class_525.java:298)
	at net.minecraft.class_525.method_19922(class_525.java:238)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1046)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
Caused by: io.netty.channel.ChannelException: failed to open a new selector
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:177)
	at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:151)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:127)
	at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:36)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
	... 49 more
Caused by: java.io.IOException: Unable to establish loopback connection
	at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
	at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.nio.ch.PipeImpl.<init>(Unknown Source)
	at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
	at java.nio.channels.Pipe.open(Unknown Source)
	at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
	at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
	at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:175)
	... 53 more
Caused by: java.net.ConnectException: Connection refused: connect
	at sun.nio.ch.Net.connect0(Native Method)
	at sun.nio.ch.Net.connect(Unknown Source)
	at sun.nio.ch.Net.connect(Unknown Source)
	at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
	at java.nio.channels.SocketChannel.open(Unknown Source)
	at sun.nio.ch.PipeImpl$Initializer$LoopbackConnector.run(Unknown Source)
	... 62 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:88)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:58)
	at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:47)
	at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:77)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:72)
	at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:59)
	at net.minecraft.class_3242.method_14348(class_3242.java:56)
	at net.minecraft.class_3528.method_15332(class_3528.java:16)
	at net.minecraft.class_3242.method_14353(class_3242.java:138)
	at net.minecraft.class_310.method_29610(class_310.java:1839)
	at net.minecraft.class_310.method_29607(class_310.java:1700)
	at net.minecraft.class_525.method_2736(class_525.java:298)
	at net.minecraft.class_525.method_19922(class_525.java:238)
	at net.minecraft.class_4185.method_25306(class_4185.java:33)
	at net.minecraft.class_4264.method_25348(class_4264.java:16)
	at net.minecraft.class_339.method_25402(class_339.java:149)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at net.minecraft.class_312.method_1611(class_312.java:92)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_525
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:127)
	at net.minecraft.class_310.method_1523(class_310.java:1046)
	at net.minecraft.class_310.method_1514(class_310.java:656)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.16.2
	Minecraft Version ID: 1.16.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 644042456 bytes (614 MB) / 1890582528 bytes (1803 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 4
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	Fabric Mods: 
		adorn: Adorn 1.11.0+1.16.2
		adventurez: AdventureZ 1.0.11
		allure: Allure 1.2.7
		angerable-patch: Angerable Patch 1.0.0-1.16.1
		aopalliance_aopalliance: aopalliance 1.0
		appleskin: AppleSkin 1.0.11
		audiooutput: AudioOutput 0.0.3
		authme: Auth Me 1.3.2
		autoconfig1u: Auto Config v1 Updated 3.2.2
		betterdroppeditems: Better Dropped Items 1.2.2-1.16.2
		bettergraves: Better Graves 0.4.1
		betterweather: Better Weather 1.0.0
		blue_endless_jankson: jankson +
		blur: Blur 1.0.6
		byg: BYG 1.0.8
		campanion: Campanion 1.2.0+build.39
		cardinal-components: Cardinal Components API 2.5.4
		cardinal-components-base: Cardinal Components API (base) 2.6.0
		cardinal-components-block: Cardinal Components API (blocks) 2.5.4
		cardinal-components-chunk: Cardinal Components API (chunks) 2.5.4
		cardinal-components-entity: Cardinal Components API (entities) 2.6.0
		cardinal-components-item: Cardinal Components API (items) 2.5.4
		cardinal-components-level: Cardinal Components API (world saves) 2.5.4
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.5.4
		cardinal-components-util: Cardinal Components API (utilities) 2.5.4
		cardinal-components-world: Cardinal Components API (worlds) 2.5.4
		cavebiomes: Cave Biomes 0.3.0
		ce_foodstuffs: Common Expansion: Foodstuffs 1.0.1
		chat_heads: Chat Heads 0.1.2+1.16.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.0
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.5.45
		cloth-api: Cloth API 1.4.8
		cloth-armor-api-v1: Cloth Armor API v1 1.4.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.8
		cloth-common-events-v1: Cloth Common Events v1 1.4.8
		cloth-config2: Cloth Config v4 4.8.1
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.8
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.8
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.8
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.8
		cloth-utils-v1: Cloth Utils v1 1.4.8
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.9.0
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.9.0
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.9.0
		com_fasterxml_jackson_dataformat_jackson-dataformat-yaml: jackson-dataformat-yaml 2.9.0
		com_fasterxml_jackson_module_jackson-module-kotlin: jackson-module-kotlin 2.9.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_google_inject_guice: guice 4.2.3
		compactstatuseffects: Compact Status Effects 1.2.2
		controlling: Controlling For Fabric 1.1.2
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		craftable_utilities: Craftable Utilities 1.0.2
		craftpresence: CraftPresence 1.6.8
		crimsonmoon: Crimson Moon 1.2.3-1.16.2
		curios: Curios API 0.0.6-1.16.2
		dankstorage: Dank Storage 1.7-1.16.2
		dark-loading-screen: Dark Loading Screen 1.5.0
		diggusmaximus: Diggus Maximus 1.3.1-1.16
		disablecustomworldsadvice: Disable Custom Worlds Advice 1.0
		dungeons_of_exile: Dungeons of Exile 1.0.1
		dynamicfps: Dynamic FPS 1.2.1
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		edit_sign: Edit Sign 2.1.1
		endreborn: End: Rebellion 1.8
		fabric: Fabric API 0.20.1+build.401-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474cfa
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea894e
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce533984e
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308364e
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f4e
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8664e
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d4e
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.0+e2e6cdad4e
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b4e
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.1+91555cd14e
		fabric-item-api-v1: Fabric Item API (v1) 1.1.0+29679fd64e
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96364e
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c64e
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c54e
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b204e
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1884e
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce994e
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d64e
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b4e
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f4e
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.7.0+432ea1884e
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea1884e
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e4e
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.4.5+fcdfdfa14e
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.0+8bcfced84e
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.0+8bcfced84e
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+e2862de64e
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d4e
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.11+fb0d9b0e4e
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104904e
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.0+432ea1884e
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf4e
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498414e
		fabric-structure-api-v1: Fabric Structure API (v1) 1.0.1+fb0d9b0e4e
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c594e
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb84e
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.2+ccce563e4e
		fabricloader: Fabric Loader 0.9.3+build.207
		fallflyinglib: FallFlyingLib 1.1.0
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.3
		fatxporbs: Fat Experience Orbs 0.0.7
		fiber: fiber 0.23.0-1
		flesh2leather: Flesh2Leather 1.0.1
		goml: Get Off My Lawn 1.1.0
		gottaclimbfast: Gotta Climb Fast! 1.0
		gunpowder-base: Gunpowder 0.2.10+1.16.2
		gunpowder-sleepvote: Gunpowder SleepVote 1.0.1+gunpowder.0.2.10.mc.1.16.2
		hardcorequesting: Hardcore Questing Mode 0.2.3
		iknowwhatimdoing: I Know What I'm Doing 3.0.0
		illuminations: Illuminations 1.0.5
		inventorysorter: Inventory Sorter 1.7.2-1.16
		invtrashslot: InvTrashSlot 1.0.1
		jankson: Jankson 3.0.1+j1.2.0
		javax_inject_javax_inject: javax.inject 1
		jumploader: Jumploader 2.0.1
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lambdynlights: LambDynamicLights 1.3.0+1.16.2
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		lessgreedypiglins: less greedy piglins 1.0.0
		libblockattributes: LibBlockAttributes 0.8.1
		libblockattributes_core: LibBlockAttributes (Core) 0.8.1
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.1
		libblockattributes_items: LibBlockAttributes (Items) 0.8.1
		libcd: LibCapableData 2.5.0+1.16.2
		libgui: LibGui 3.0.0-beta.1+1.16.2-rc2
		library_of_exile: Library of Exile 1.0.4
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.5.3
		lithium: Lithium 0.5.4
		mambience: MAmbience 2.1.0+1.16.2
		minecraft: Minecraft 1.16.2
		mmorpg: Age of Exile 1.3.12
		modmenu: Mod Menu 1.14.6+build.31
		mostructures: Mo' Structures 1.0.0-pre3+mc.1.16.2
		musicdr: Music Duration Reducer 1.1.1
		mysql_mysql-connector-java: mysql-connector-java 5.1.46
		nbtcrafting: NBT Crafting 2.0.0-rc.6+mc1.16.2-pre1
		numericping: NumericPing 1.0.2-fabric1.16.2
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_exposed_exposed-core: exposed-core 0.23.1
		org_jetbrains_exposed_exposed-java-time: exposed-java-time 0.23.1
		org_jetbrains_exposed_exposed-jdbc: exposed-jdbc 0.23.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		org_postgresql_postgresql: postgresql 42.2.2
		org_slf4j_slf4j-api: slf4j-api 1.8.0-beta1
		org_xerial_sqlite-jdbc: sqlite-jdbc 3.28.0
		org_yaml_snakeyaml: snakeyaml 1.26
		origins: Origins 1.16.3-0.3.8
		origins-classes: Origins: Classes 1.16.2-1.0.1
		parchment: Parchment 1.0.2+1.15.2
		patchouli: Patchouli 1.16-40-FABRIC
		petowner: Pet Owner 1.16.2+-1.6.1
		phosphor: Phosphor 0.6.0+build.7
		polymorph: Polymorph 0.0.5-1.16.3
		projectsavethepets: Project: Save the Pets! 1.0.1+minecraft-1.16.2
		randomconfigs: RandomConfigs 1.16.2-1.4.2.2-fabric
		randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.2-1.5.3
		resourceloader: Fabric Resource Loader 1.1.1
		respawnablepets: Respawnable Pets 6
		roughlyenoughitems: Roughly Enough Items 5.4.2
		roughlyenoughitems-api: REI (API) 5.4.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.4.2
		roughlyenoughitems-runtime: REI (Runtime) 5.4.2
		roughlyenoughresources: Roughly Enough Resources 2.1.0
		rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
		satin: Satin 1.4.1
		spruceui: SpruceUI 1.6.2
		structure-helpers: Structure Helpers 3.0.0
		the_bumblezone: The Bumblezone - Fabric 1.16.2-2.2.4
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trade: Trade 1.1.0
		trapexpansion: Trap Expansion 1.3.2
		villagerfix: Villager Fix 1.3.1+1.16.3
		waila: Hwyla 1.9.22
		ward_blocks: Ward Blocks 1.0.15
		whereisit: Where Is It 1.8.3
		wildworld: Wild World 1.3.0+1.16.2
		window_title_changer: Window Title Changer 2.1.0-1.16.2
		xaerominimap: Xaero's Minimap 20.22.0
		xaeroworldmap: Xaero's World Map 1.10.3
	Patchouli open book context: n/a
	Launched Version: Jumploader
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 456.38, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric/gunpowder-base, fabric/fabric-keybindings-v0, fabric/dynamicsoundfilters, fabric/fabricloader, fabric/satin, fabric/adventurez, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/controlling, fabric/xaeroworldmap, fabric/diggusmaximus, fabric/lambdynlights, fabric/randompatches, fabric/roughlyenoughresources, fabric/waila, fabric/fabric-blockrenderlayer-v1, fabric/libblockattributes_items, fabric/fabric, fabric/fabric-networking-v0, fabric/cleancut, fabric/fabric-screen-handler-api-v1, fabric/repurposed_structures, fabric/modmenu, fabric/musicdr, fabric/blur, fabric/fabric-tool-attribute-api-v1, fabric/roughlyenoughitems-runtime, fabric/structure-helpers, fabric/fabric-crash-report-info-v1, fabric/resourceloader, fabric/fabric-events-interaction-v0, fabric/whereisit, fabric/curios, fabric/fabric-language-kotlin, fabric/nbtcrafting, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/endreborn, fabric/fabric-resource-loader-v0, fabric/compactstatuseffects, fabric/trapexpansion, fabric/clear-skies, fabric/libblockattributes_fluids, fabric/authme, fabric/fabric-registry-sync-v0, fabric/adorn, fabric/fabric-mining-levels-v0, fabric/the_bumblezone, fabric/fabric-item-groups-v0, fabric/fabric-models-v0, fabric/fabric-renderer-api-v1, fabric/parchment, fabric/inventorysorter, fabric/libcd, fabric/flesh2leather, fabric/mambience, fabric/cavebiomes, fabric/allure, fabric/mmorpg, fabric/lithium, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/randomconfigs, fabric/libblockattributes, fabric/fabric-rendering-data-attachment-v1, fabric/campanion, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/dynamicfps, fabric/libblockattributes_core, fabric/fabric-networking-blockentity-v0, fabric/jankson, fabric/invtrashslot, fabric/betterdroppeditems, fabric/fabric-renderer-indigo, fabric/dark-loading-screen, fabric/roughlyenoughitems, fabric/fabric-item-api-v1, fabric/numericping, fabric/libgui, fabric/xaerominimap, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/spruceui, fabric/autoconfig1u, fabric/fabric-content-registries-v0, fabric/bettergraves, fabric/fabric-tag-extensions-v0, fabric/fastfurnace, fabric/window_title_changer, fabric/fabric-events-lifecycle-v0, fabric/fabric-object-builders-v0
	Current Language: English (US)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by mahjerion** [comment]
Hey does it happen everytime you try to boot up or just this once? Also next time could you pastebin the crash log instead of pasting it in the report :P

**Comment by JFMillerUSA** [comment]
figured it out, didn't read the readme about the datapack folder, sorry

**Comment by mahjerion** [comment]
glad you got it!
