### ISSUE TITLE
Fresh server install failing to launch

### ISSUE THREAD

**Issue by YoItSoul** [mahjerion/Craft-to-Exile-Harmony#41]
Launching on a Ubuntu.
Linux
SMP 
x86_64
GNU/Linux

We've just installed the latest version of Craft to Exile (Server) and we are unfortunately meeting some hostility in launching the content. Any help would be much appreciated!

This is the .sh we start the server with to keep a screen on the console.

```
#!/bin/sh
if [ -z "$STY" ]
then
	# Not in a screen, try to connect to minecraft screen
	screen -d -r minecraft
	if [ $? -ne 0 ]
	then
		# The screen does not exit -- Create and switch to it
		screen -S minecraft
	fi

	# The screen was closed or was appropriated
	exit 0
fi

case $STY in
	*.minecraft )
		# This script was started from the minecraft screen
		# Start minecraft
		ulimit -c unlimited
		echo Time to exile the players!
		cd /home/game/exiled/
		echo --- $(date) --- >> auto_restart.log
		while :
		do
			/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -XX:+UseG1GC -Xmx15G -Xms15G -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -jar fabric-server-launch.jar nogui
			echo Restarting in 10 seconds
			echo To prevent restarting press ctrl c
			sleep 10
			echo $(date) >> auto_restart.log
		done
		;;
	* )
		# This script was started from another screen
		echo "Warning: This script was started from another screen: $STY"
		exit 0
		;;
esac
```

**The server launches and this is the crash we get. (Sourced from latest.log)**

```
[22:19:26] [main/INFO]: Loading for game Minecraft 1.16.2
[22:19:26] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[22:19:30] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-7/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-6/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-6/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-6/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-6/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-4/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-4/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-2/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:30] [ForkJoinPool-1-worker-5/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-2/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:30] [ForkJoinPool-1-worker-5/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:30] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:30] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-chunk" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:30] [ForkJoinPool-1-worker-3/WARN]: The mod "cardinal-components-world" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:30] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-1/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-5/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:30] [ForkJoinPool-1-worker-5/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:30] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-1/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 8 column 12
[22:19:31] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-7/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-5/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-5/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: The mod "cardinal-components-util" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-1/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-7/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-7/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-3/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-3/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-5/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-6/WARN]: The mod "cardinal-components-world" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-5/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-5/WARN]: The mod "controlling" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 6 column 9
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [ForkJoinPool-1-worker-2/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-2/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-6/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[22:19:31] [ForkJoinPool-1-worker-6/WARN]: "fabric.mod.json" from mod autoconfig1u did not have "schemaVersion" as first field.
[22:19:31] [ForkJoinPool-1-worker-4/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[22:19:31] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: fatxporbs requires {fabricloader @ [>=0.10.6]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:173) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:739) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:206) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:196) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:127) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:170) ~[fabric-server-launch.jar:?]
	... 12 more

```

**Comment by YoItSoul** [comment]
I see that an update was just pushed, sorry if I caught you before a server update!

**Comment by mahjerion** [comment]
No worries - there was a fix for that too. As for 1.3.6, curseforge refuses to review any server files atm for some dumb reason. But here are the 1.3.6 files: https://github.com/mahjerion/Craft-to-Exile-Harmony-Server/archive/1.3.6.zip
