### ISSUE TITLE
[BUG] Crash Report: Mending Sword enchantment.

### ISSUE THREAD

**Issue by Raspyutin** [mahjerion/Craft-to-Exile-Harmony#67]
**Technical Specs (please complete the following information):**
 - Craft to Exile Version 2.0.3c
 - World Type multiplayer
 - RAM Allocation 4gb?

**Describe the bug**
Game crashes when trying to enchant sword with Mending and other enchantments (currently, enchanting with books seems bugged).

**To Reproduce**
Start with clean Gear item (used Royal Sword)
Enchant at anvil with book of Mending
Enchant at anvil with other book, causing crash.

**Expected behavior**
Normal enchantment behavior.

Crash report:
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2/3/21 11:11 AM
Description: mouseClicked event handler

java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:438)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_471
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:438)
	at net.minecraft.class_312.method_1601(class_312.java:92)
	at net.minecraft.class_312.method_22686(class_312.java:162)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22684(class_312.java:162)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:109)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at link.infra.jumploader.Jumploader.onLoad(Jumploader.java:171)
	at cpw.mods.modlauncher.TransformationServiceDecorator.onLoad(TransformationServiceDecorator.java:53)
	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$loadTransformationServices$11(TransformationServicesHandler.java:131)
	at java.util.HashMap$Values.forEach(Unknown Source)
	at cpw.mods.modlauncher.TransformationServicesHandler.loadTransformationServices(TransformationServicesHandler.java:131)
	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:56)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:76)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['Jubban'/40794, l='ClientLevel', x=-1204.73, y=14.00, z=410.06]]
	Chunk stats: Client Chunk Cache: 529, 303
	Level dimension: minecraft:overworld
	Level spawn location: World: (-1068,66,155), Chunk: (at 4,4,11 in -67,9; contains blocks -1072,0,144 to -1057,255,159), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
	Level time: 7651659 game time, 9102218 day time
	Server brand: Fabric/Gunpowder
	Server type: Non-integrated multiplayer server

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4114887624 bytes (3924 MB) / 14043054080 bytes (13392 MB) up to 15077474304 bytes (14379 MB)
	CPUs: 16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms8496m -Xmx16176m
	Fabric Mods: 
		adorn: Adorn 1.12.2+1.16.4
		adventurez: AdventureZ 1.1.5
		allure: Allure 1.2.8
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		appleskin: AppleSkin 1.0.11
		architectury: Architectury 1.5.104
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		audiooutput: AudioOutput 0.0.3
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		balance_of_exile: Balance of Exile 1.0.3
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		betterend: Better End 0.8.8-beta
		betternether: Better Nether 5.0.4
		betterpingdisplay: Better Ping Display 1.1
		betterweather: Better Weather 1.0.0
		biome_locator: Biome Locator 1.0.0
		blue_endless_jankson: jankson 1.2.0
		blur: Blur (Fabric) 2.0.0
		byg: BYG 1.1.3
		campanion: Campanion 1.3.2
		cardinal-components-base: Cardinal Components API (base) 2.7.10
		cardinal-components-chunk: Cardinal Components API (chunks) 2.6.0
		cardinal-components-entity: Cardinal Components API (entities) 2.7.10
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-util: Cardinal Components API (utilities) 2.6.0
		cardinal-components-world: Cardinal Components API (worlds) 2.6.0
		cavebiomes: Cave Biomes 0.5.1
		charm: Charm 2.2.2
		charmonium: Charmonium 2.2.2
		chat_heads: Chat Heads 0.2.2+1.16.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cinderscapes: Cinderscapes 1.3.2
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.5.55
		cloth-api: Cloth API 1.4.9
		cloth-armor-api-v1: Cloth Armor API v1 1.4.9
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.9
		cloth-common-events-v1: Cloth Common Events v1 1.4.9
		cloth-config2: Cloth Config v4 4.8.3
		cloth-datagen-api-v1: Cloth Datagen v1 1.4.9
		cloth-durability-bar-api-v1: Cloth Durability Bar API v1 1.4.9
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		cloth-scissors-api-v1: Cloth Scissors API v1 1.4.9
		cloth-utils-v1: Cloth Utils v1 1.4.9
		com_electronwill_night-config_core: core 3.6.2
		com_electronwill_night-config_toml: toml 3.6.2
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		compactstatuseffects: Compact Status Effects 1.2.3
		controlling: Controlling For Fabric 1.1.2
		craftablehorsearmour: Craftable Horse Armour & Saddle 1.16-1.3-Fabric
		craftpresence: CraftPresence 1.7.6
		creeperspores: Creeper Spores 1.4.1
		crimsonmoon: Crimson Moon 1.2.3-1.16.2
		curios: Curios API 0.0.10-1.16.3
		dankstorage: Dank Storage 1.9a-1.16.3
		diggusmaximus: Diggus Maximus 1.4.2-1.16.3
		disable_custom_worlds_advice: Disable Custom Worlds Advice 1.2
		dragonloot: DragonLoot 1.0.4
		dungeons_of_exile: Dungeons of Exile 1.1.1
		dynamicfps: Dynamic FPS 2.0.1
		dynamicsoundfilters: Dynamic Sound Filters 1.2.0+1.16.5
		editsign: Edit Sign 2.2.0
		enchantmentdescriptions: Enchantment Descriptions 1.0.0
		endreborn: End: Rebellion 1.8
		fabric: Fabric API 0.29.4+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-furnaces: Fabric Furnaces 1.3.3-1.16.4
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-language-kotlin: Fabric Language Kotlin 1.4.21+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		fancymenu: FancyMenu 1.6.0
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.3
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		flan: Flan 1.16.2-1.2.2
		flesh2leather: Flesh2Leather 1.0.2
		go-fish: Go Fish 1.2.0-beta-1.16.4
		gottaclimbfast: Gotta Climb Fast! 1.0
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		hardcorequesting: Hardcore Questing Mode 1.16.2+5.5.4
		heartbond: Heartbond 1.0.0
		hypnos: Hypnos 0.1.1
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		illuminations: Illuminations 1.4.4
		inventoryprofiles: Inventory Profiles 0.4.2
		invtrashslot: InvTrashSlot 1.0.2
		ironchest: Iron Chests 1.1.3
		itemflexer: ItemFlexer 1.1.0
		itemscroller: Item Scroller 0.15.0-dev.20210111.205029
		jankson: Jankson 3.0.1+j1.2.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		jumploader: Jumploader 2.1.2
		konkrete: Konkrete 1.1.1
		kubejs: KubeJS 1605.3.5-build.157
		kyrptconfig: Kytpt Config 1.1.4-1.16
		lambdynlights: LambDynamicLights 1.3.4+1.16
		leaf-decay: Leaf Decay 1.2.0-1.16.1
		libblockattributes: LibBlockAttributes 0.8.5
		libblockattributes_core: LibBlockAttributes (Core) 0.8.5
		libblockattributes_fluids: LibBlockAttributes (Fluids) 0.8.5
		libblockattributes_items: LibBlockAttributes (Items) 0.8.5
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		library_of_exile: Library of Exile 1.0.6
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.6.1
		lithium: Lithium 0.6.1
		lootbeams: Lootbeams 1.0.2
		malilib: MaLiLib 0.10.0-dev.21+arne.2
		microconfig: Microconfig 1.0.3
		minecraft: Minecraft 1.16.4
		mmorpg: Age of Exile 1.7.10
		modmenu: Mod Menu 1.14.15
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		musicdr: Music Duration Reducer 1.1.3
		nbtcrafting: NBT Crafting 2.0.3+mc1.16.4
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.4.2
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.4.2
		org_yaml_snakeyaml: snakeyaml 1.25
		origins: Origins 0.4.6
		origins-classes: Origins: Classes 1.1.0
		patchouli: Patchouli 1.16.4-48-FABRIC
		petowner: Pet Owner 1.7.1-1.16.2+
		phosphor: Phosphor 0.7.0+build.10
		polymorph: Polymorph 0.0.5-1.16.3
		projectsavethepets: Project: Save the Pets! 1.0.2+minecraft-1.16.4
		randompatches: RandomPatches 1.16.1-0.0.0.5-fabric
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		repurposed_structures: Repurposed Structures 1.16.4-1.7.4
		rhino: Rhino 1.7.13
		roughlyenoughitems: Roughly Enough Items 5.9.1
		roughlyenoughitems-api: REI (API) 5.9.1
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.9.1
		roughlyenoughitems-runtime: REI (Runtime) 5.9.1
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		satin: Satin 1.5.1
		smoothboot: Smooth Boot 1.16.4-1.4.0
		spruceui: SpruceUI 2.0.4+1.16
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		structure-helpers: Structure Helpers 3.0.0
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.4
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.4
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.1.0+build.4
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.4
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.4
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.4
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.1
		terrestria: Terrestria 2.1.6
		the_bumblezone: The Bumblezone - Fabric 1.16.5-2.2.17
		tk_valoeghese_zoesteriaconfig: ZoesteriaConfig 1.3.2
		trade: Trade 1.1.3
		transferchestmod: Transfer Chest 1.1.3
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.3.1
		ttg_fallfest: FallFest 2020 0.1.1
		vanguard: Vanguard 1.0.5
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		ward_blocks: Ward Blocks 1.0.20
		waystones: Waystones 1.1.1.1
		whereisit: Where Is It 1.9.2
		wildworld: Wild World 1.3.0+1.16.2
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		xaerominimap: Xaero's Minimap 21.1.1
		xaeroworldmap: Xaero's World Map 1.11.10
		xp_storage: XP Storage 1.4+1.16.4
		yosbr: YOSBR 0.1.1
		zoob: Monster Of The Ocean Depths 2.5.0
	Patchouli open book context: n/a
	Launched Version: MultiMC5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 460.79, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, kubejs:resource_pack
	Current Language: English (US)
	CPU: 16x AMD Ryzen 7 3800X 8-Core Processor

**Comment by mahjerion** [comment]
Haha next time you should pastebin it so its less cluttered! Thanks though, I think i see the issue.
